### ISSUE TITLE
2421 segmentation fault  python3

### ISSUE THREAD

**Issue by maciej-nawrocki** [sunnypatell/sunnify-spotify-downloader#2]
I'm trying to set it up on Macc Sonoma 14.5 (Intel based).

I downloaded and installed python 3.12.4.

I do have pip:

`pip3 --version
pip 24.0 from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip (python 3.12)
` 

Installation went ok, without any errors. But when I exectue:

`python3 Spotify_Downloader.py`

I get:

`[1]    2542 segmentation fault  python3 Spotify_Downloader.py`

**Comment by sunnypatell** [comment]
Install the required dependencies, after cloning the repo (cd into the parent dir) and run:

pip install -r req.txt

also run the fie natively how you would on Sonoma (syntax for CLI is a little different)
