### ISSUE TITLE
Hey ihave got the following bug:

### ISSUE THREAD

**Issue by zschorni** [sunnypatell/sunnify-spotify-downloader#4]
I have got the following report:

sunnify-spotify-downloader % pip3 install -r req.txt
Collecting altgraph==0.17.3 (from -r req.txt (line 1))
Using cached https://files.pythonhosted.org/packages/cc/ff/88d277ba936d226b0f6dbd6711145f90fcfeed3aa9455c1c2f62c8ffec5b/altgraph-0.17.3-py2.py3-none-any.whl
Collecting certifi==2023.7.22 (from -r req.txt (line 2))
Using cached https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl
Collecting charset-normalizer==3.2.0 (from -r req.txt (line 3))
Could not find a version that satisfies the requirement charset-normalizer==3.2.0 (from -r req.txt (line 3)) (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
No matching distribution found for charset-normalizer==3.2.0 (from -r req.txt (line 3))

**Comment by zschorni** [comment]
I have got the following report:   

 sunnify-spotify-downloader % pip3 install -r req.txt
Collecting altgraph==0.17.3 (from -r req.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/cc/ff/88d277ba936d226b0f6dbd6711145f90fcfeed3aa9455c1c2f62c8ffec5b/altgraph-0.17.3-py2.py3-none-any.whl
Collecting certifi==2023.7.22 (from -r req.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl
Collecting charset-normalizer==3.2.0 (from -r req.txt (line 3))
  Could not find a version that satisfies the requirement charset-normalizer==3.2.0 (from -r req.txt (line 3)) (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
No matching distribution found for charset-normalizer==3.2.0 (from -r req.txt (line 3))

**Comment by sunnypatell** [comment]
# Fresh Installation of `req.txt` Dependencies and Clearing Pip Cache

Follow these steps to uninstall all cached pip packages and perform a fresh installation of your dependencies from `req.txt`.

1. Clear the Pip Cache:
   Run the following command to remove all cached files for packages installed via pip:
`pip cache purge`

2. Uninstall All Currently Installed Packages:
To remove all currently installed pip packages, run:
`pip uninstall -r req.txt -y`

3. Reinstall Dependencies from `req.txt`:
After clearing the cache and uninstalling the packages, you can reinstall your dependencies using:
`pip install -r req.txt`


If you still have issues, lucky for you, if you're using Windows, I've already built an `.exe` version. You can run the executable located at the relative path:

`**sunnify-spotify-downloader\dist\Sunnify (Spotify Downloader).exe**`

All dependencies are packaged within that executable, so you can run it without needing to install any additional packages.
